/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package techmis;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author shan
 */
public class AdminLogin extends javax.swing.JFrame {

    /**
     * Creates new form ToLogin
     */
    public AdminLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lecBar = new javax.swing.JPanel();
        username = new javax.swing.JTextField();
        lecName = new javax.swing.JLabel();
        lecPwd = new javax.swing.JLabel();
        clear = new javax.swing.JButton();
        login = new javax.swing.JButton();
        pass = new javax.swing.JPasswordField();
        error = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admin.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 110, 120));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 90, 90));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("Admin Login");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, 50));

        lecBar.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout lecBarLayout = new javax.swing.GroupLayout(lecBar);
        lecBar.setLayout(lecBarLayout);
        lecBarLayout.setHorizontalGroup(
            lecBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        lecBarLayout.setVerticalGroup(
            lecBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(lecBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 410, 10));

        username.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 190, 40));

        lecName.setBackground(new java.awt.Color(255, 255, 255));
        lecName.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lecName.setForeground(new java.awt.Color(255, 255, 255));
        lecName.setText("User Name");
        jPanel1.add(lecName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 160, 30));

        lecPwd.setBackground(new java.awt.Color(255, 255, 255));
        lecPwd.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lecPwd.setForeground(new java.awt.Color(255, 255, 255));
        lecPwd.setText("Password");
        jPanel1.add(lecPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 160, 30));

        clear.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel1.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, -1, -1));

        login.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        login.setText("LOGIN");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel1.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, -1, -1));

        pass.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 190, 40));

        error.setBackground(new java.awt.Color(254, 254, 254));
        error.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        error.setForeground(new java.awt.Color(254, 254, 254));
        jPanel1.add(error, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 270, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        LoginHome log = new LoginHome();
        log.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        username.setText(null);
        pass.setText(null);
    }//GEN-LAST:event_clearActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed

        String user_name = username.getText().trim();
        String password = pass.getText().trim();

        if(user_name.isEmpty() && password.isEmpty())
        {
            error.setText("Please enter both fields!!!");
        }
        else if(password.isEmpty())
        {
            error.setText("Please enter password!!!");
        }
        else if(user_name.isEmpty())
        {
            error.setText("Please enter user name!!!");
        }
        else{
            ResultSet rs=null;
            try{
                Connection con = MyConnection.getConnection();
                String sql = "select * from user where user_id='"+user_name+"'";
                PreparedStatement ps = con.prepareStatement(sql);
                rs = ps.executeQuery();

                //if(rs.getString("user_pwd")== password){
                    if(rs.next()==true)
                    {
                        UpdateAdminProfile ad = new UpdateAdminProfile();
                        ad.setId(rs.getString("user_id"));
                        
                        WelcomeAdmin inter = new WelcomeAdmin();
                        inter.setVisible(true);
                        this.setVisible(false);
                        
                    }
                    else{
                        error.setText("invalid user");
                    }
                    //}else{
                    //    error.setText("invalid password");
                    //}
            }
            catch(Exception e)
            {
                error.setText("system error");
            }
        }
        
        /*PreparedStatement st;
        ResultSet rs;
        
        String user = username.getText();
        String password = String.valueOf(pass.getPassword()); 
        
        try {
            Connection con = MyConnection.getConnection();
            String sql = "select * from user where user_id='"+username+"'";
            
            st = con.prepareStatement(sql);
            
            st.setString(1, user);
            st.setString(2, password);
            rs = st.executeQuery();
            
            if (rs.next()) {
                WelcomeAdmin inter = new WelcomeAdmin();
                inter.setVisible(true);
                this.setVisible(false);
            }else{
                JOptionPane.showMessageDialog(null,"Invalid username or password","Login error",2);
            }
        
        } catch (SQLException ex) {
            Logger.getLogger(AdminLogin.class.getName()).log(Level.SEVERE, null, ex);
        }*/
        
                
    }//GEN-LAST:event_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear;
    private javax.swing.JLabel error;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel lecBar;
    private javax.swing.JLabel lecName;
    private javax.swing.JLabel lecPwd;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
