/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package techmis;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author shan
 */
public class Marks extends javax.swing.JFrame {
            Connection con = null;
            ResultSet rs = null;
            PreparedStatement pst;
    /**
     * Creates new form Marks
     */
    public Marks() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        StId = new javax.swing.JTextField();
        Search = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Mid = new javax.swing.JTextField();
        SubId = new javax.swing.JTextField();
        Q1 = new javax.swing.JTextField();
        Q2 = new javax.swing.JTextField();
        Q3 = new javax.swing.JTextField();
        Q4 = new javax.swing.JTextField();
        Ass1 = new javax.swing.JTextField();
        Ass2 = new javax.swing.JTextField();
        Ass3 = new javax.swing.JTextField();
        Theory = new javax.swing.JTextField();
        Practical = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        update = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(900, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Back.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        jPanel1.add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 30, -1, -1));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("Student ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        StId.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jPanel1.add(StId, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 190, 40));

        Search.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        jPanel1.add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, -1, -1));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("Mid Exam");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 310, -1, -1));

        Mid.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jPanel1.add(Mid, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 350, 130, 40));

        SubId.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jPanel1.add(SubId, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 190, 40));

        Q1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jPanel1.add(Q1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 130, 40));

        Q2.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jPanel1.add(Q2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 130, 40));

        Q3.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jPanel1.add(Q3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 130, 40));

        Q4.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jPanel1.add(Q4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 350, 130, 40));

        Ass1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jPanel1.add(Ass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, 130, 40));

        Ass2.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jPanel1.add(Ass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 490, 130, 40));

        Ass3.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jPanel1.add(Ass3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 490, 130, 40));

        Theory.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jPanel1.add(Theory, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 490, 130, 40));

        Practical.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jPanel1.add(Practical, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 490, 130, 40));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setText("Subject ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setText("Quiz 1");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, -1, -1));

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setText("Quiz 2");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, -1, -1));

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(254, 254, 254));
        jLabel6.setText("Quiz 3");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, -1, -1));

        jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(254, 254, 254));
        jLabel7.setText("Quiz 4");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, -1, -1));

        jLabel8.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(254, 254, 254));
        jLabel8.setText("Practical");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 450, -1, -1));

        jLabel9.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(254, 254, 254));
        jLabel9.setText("Theory");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 450, -1, -1));

        jLabel10.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(254, 254, 254));
        jLabel10.setText("Assesment 3");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 450, -1, -1));

        jLabel11.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(254, 254, 254));
        jLabel11.setText("Assesment 2");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, -1, -1));

        jLabel12.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(254, 254, 254));
        jLabel12.setText("Assesement 1");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, -1, -1));

        add.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 580, 90, -1));

        update.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 580, -1, -1));

        jLabel14.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(254, 254, 254));
        jLabel14.setText("Marks");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        WelcomeLecturer lec = new WelcomeLecturer();  
        lec.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        MarkClass co = new MarkClass();

        co.setId(StId.getText());
        co.setSub(SubId.getText());
        co.setQ1(Q1.getText());
        co.setQ2(Q2.getText());
        co.setQ3(Q3.getText());
        co.setQ4(Q4.getText());
        co.setA1(Ass1.getText());
        co.setA2(Ass2.getText());
        co.setA3(Ass3.getText());
        co.setMid(Mid.getText());
        co.setPr(Practical.getText());
        co.setTh(Theory.getText());
        

        co.editMarks();

        clear();
    }//GEN-LAST:event_updateActionPerformed
 
    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        String id = StId.getText();
        String sub = SubId.getText();
        
        MarkClass co = new MarkClass();

        if(!id.isEmpty() && !sub.isEmpty())
        {
            ResultSet rs = co.searchMarks(id,sub);
            try {
                if(rs.next())
                {
                    Q1.setText(rs.getString("q1"));
                    Q2.setText(rs.getString("q2"));  
                    Q3.setText(rs.getString("q3"));  
                    Q4.setText(rs.getString("q4"));
                    Ass1.setText(rs.getString("ass1"));
                    Ass2.setText(rs.getString("ass2"));
                    Ass3.setText(rs.getString("ass3"));
                    Mid.setText(rs.getString("mid"));
                    Theory.setText(rs.getString("theory"));
                    Practical.setText(rs.getString("practical"));
                }
                else
                {
                    javax.swing.JOptionPane.showMessageDialog(null, "Data not in the database");
                    clear();
                }
            }
            catch (Exception ex) {
                JOptionPane.showMessageDialog(null,"error....");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Please enter student id and subject id");
        }
    }//GEN-LAST:event_SearchActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        MarkClass m = new MarkClass();


        String id = StId.getText().trim();
        String sub = SubId.getText().trim();

        if(!sub.equals("") && !id.equals("")){
            try {
                m.setId(StId.getText());
                m.setSub(SubId.getText());
                m.setQ1(Q1.getText());
                m.setQ2(Q2.getText());
                m.setQ3(Q3.getText());
                m.setQ4(Q4.getText());
                m.setA1(Ass1.getText());
                m.setA2(Ass2.getText());
                m.setA3(Ass3.getText());
                m.setMid(Mid.getText());
                m.setTh(Theory.getText());
                m.setPr(Practical.getText());

                m.create();
                clear();
            } 
            catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(null, e);
            }
        }
          else
          {
              javax.swing.JOptionPane.showMessageDialog(null, "Please enter Student ID and Subject ID ");
           }
    }//GEN-LAST:event_addActionPerformed

    public void clear(){
        StId.setText("");
        SubId.setText("");
        Q1.setText("");
        Q2.setText("");
        Q3.setText("");
        Q4.setText("");
        Ass1.setText("");
        Ass2.setText("");
        Ass3.setText("");
        Mid.setText("");
        Theory.setText("");
        Practical.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Marks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Marks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Marks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Marks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Marks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Ass1;
    private javax.swing.JTextField Ass2;
    private javax.swing.JTextField Ass3;
    private javax.swing.JButton Back;
    private javax.swing.JTextField Mid;
    private javax.swing.JTextField Practical;
    private javax.swing.JTextField Q1;
    private javax.swing.JTextField Q2;
    private javax.swing.JTextField Q3;
    private javax.swing.JTextField Q4;
    private javax.swing.JButton Search;
    private javax.swing.JTextField StId;
    private javax.swing.JTextField SubId;
    private javax.swing.JTextField Theory;
    private javax.swing.JButton add;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
