package techmis;


import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author tg375
 */
public class StudentViewCA extends javax.swing.JFrame {

   
    public StudentViewCA() {
        
        initComponents();
        subject();
    }

    
     PreparedStatement pdst;
     MyConnection con=new MyConnection();
     DefaultTableModel tmodel;

    String stid;
    String sub;
     
   

   

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        stid_txt = new javax.swing.JTextField();
        sub_comb = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ca_table = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("sid");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 100, 28));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("subject");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 100, 31));
        jPanel1.add(stid_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 160, 40));

        jPanel1.add(sub_comb, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 160, 50));

        jButton2.setText("show  ca  result");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 139, 54));

        ca_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "StudentID", "Subject Code", "quiz result", "assignment", "mid", "total CA marks", "status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ca_table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 670, 220));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setText("CA Result View ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        jButton3.setText("clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 590, 99, 38));

        jButton4.setText("View final grade");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 590, 131, 38));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 60, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
         getmarks(get_text(stid),get_text2(sub));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        //clear raws in jtable
         for(int c=tmodel.getRowCount()-1;c>=0;c--){
                            tmodel.removeRow(c);
                        }
         
         //and clear the combo box and txtfield
         stid_txt.setText("");
         sub_comb.setSelectedIndex(-1);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        StudentViewFinalMarks fm=new StudentViewFinalMarks();
        this.hide();
        fm.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       WelcomeLecturer notice = new WelcomeLecturer();
       notice.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    //get subject names for combo box
    private void subject(){
        try {
            pdst=con.getConnection().prepareStatement("select * from subject");
             ResultSet rs=pdst.executeQuery();
             sub_comb.removeAllItems();
            
             while(rs.next()){
                 sub_comb.addItem(rs.getString(3));
             }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(StudentViewCA.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    
   //get subject code from database
    public String getdsubid(){
        
            
            String subid="";
            String query1="select * from subject  where sub_name=?";
            try {
                pdst=con.getConnection().prepareStatement(query1);
                pdst.setString(1, sub);
            
            ResultSet rs=pdst.executeQuery();
            if(rs.next()==false){
                JOptionPane.showMessageDialog(this, "Not Valid Subject Number");
            }else{
                while(rs.next()){
                    subid=rs.getString("sub_id");
                }
            }
            } catch (SQLException ex) {
                Logger.getLogger(StudentViewCA.class.getName()).log(Level.SEVERE, null, ex);
            }
            
       return subid;
    }
   public String get_text(String stid){ 
        stid=stid_txt.getText();
        //sub=sub_comb.getSelectedItem().toString();
        return stid;
        
   }
   public String get_text2(String sub){ 
        //stid=stid_txt.getText();
        sub=sub_comb.getSelectedItem().toString();
        return sub;
        
   }
   
  
    public double getmarks(String stid,String sub){
        
        String status = "";
        double total=0;
        
       // String stid=stid_txt.getText();
      //  String sub=sub_comb.getSelectedItem().toString();
        double q1 = 0;
        double q2=0;
        double q3=0;
        double q4=0;
        double ass1=0;
        double ass2=0;
        double ass3=0;
        double mid=0;
        String subid="";
       
        
            
        String query1="select * from subject  where sub_name=?";
        try {
                pdst=con.getConnection().prepareStatement(query1);
                pdst.setString(1, sub);
            
            ResultSet rs=pdst.executeQuery();
            while(rs.next()){
                subid=rs.getString("sub_id");
            
            }
            String query2="select * from CA_marks where sub_id=? and st_id=?";
        
            pdst=con.getConnection().prepareStatement(query2);
            //caal to getsubid function
             pdst.setString(1, subid); 
             pdst.setString(2, stid);
            
            rs=pdst.executeQuery();
            
            //get result for result set
            while(rs.next()){
                q1=rs.getDouble("q1");
                q2=rs.getDouble("q2");
                q3=rs.getDouble("q3");
                q4=rs.getDouble("q4");
                ass1=rs.getDouble("ass1");
                ass2=rs.getDouble("ass2");
                ass3=rs.getDouble("ass3");
                mid=rs.getDouble("mid");
                        
            //assign quiz marks to array
            double[] quiz={q1,q2,q3,q4};
            double[] assignment={ass1,ass2,ass3};
            
            //get min value from quiz marks
            double min=quiz[0];
            double qtot=0;
            for(int i=0;i<4;i++){
                double no=quiz[i];
                if(min>no){
                    min=no;
                }
            }
            
            //get quiz total
            for(int j=0;j<4;j++){
                 if(min!=quiz[j]){
                     qtot= qtot  + quiz[j];
                }
            }
            
            //get assignment total
            double asstot=0;
             for(int c=0;c<3;c++){
                 
                     asstot= asstot  + assignment[c];
                
            }
            
            //get quiz marks
            double quiz_marks=qtot/3;
            double ass_marks=asstot/3;
            
            //get full ca marks total
            total=(quiz_marks+ass_marks+mid)/3;
            
            if(total>=50){
                status="PASS";
            }
            else{
                 status = "FAIL";
            }
            
            //new DecimalFormat("0.00").format(quiz_marks);
            
            
            tmodel=(DefaultTableModel)ca_table.getModel();
                    tmodel.addRow(new Object[]{
                        stid,
                        subid,
                        quiz_marks,
                        ass_marks,
                        mid,
                        total,
                        status
                        
                    });
  
            }
        } catch (SQLException ex) {
            Logger.getLogger(StudentViewCA.class.getName()).log(Level.SEVERE, null, ex);
        }
        
             return total;  
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentViewCA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentViewCA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentViewCA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentViewCA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentViewCA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ca_table;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField stid_txt;
    private javax.swing.JComboBox sub_comb;
    // End of variables declaration//GEN-END:variables


public void connectFinalResult()  {
   // double catotal=getmarks(String stid,String sub);
  // new StudentViewFinalMarks(getmarks());
   //ViewFinalMarks vfm=new StudentViewFinalMarks(getmarks().total,status);
}






}
