/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package techmis;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author shan
 */
public class StudentEligibility extends javax.swing.JFrame {

    /**
     * Creates new form StudentEligibility
     */
    public StudentEligibility() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        SubId = new javax.swing.JTextField();
        StId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Serach = new javax.swing.JButton();
        Practical = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Eligibility = new javax.swing.JLabel();
        Attendance = new javax.swing.JLabel();
        Pra = new javax.swing.JLabel();
        Att = new javax.swing.JLabel();
        PraCount = new javax.swing.JLabel();
        AttCount = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(900, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("Student Eligibility");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        Back.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        jPanel1.add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 40, -1, -1));

        SubId.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jPanel1.add(SubId, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 280, 50));

        StId.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jPanel1.add(StId, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 280, 50));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("Subject ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, -1, -1));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setText("Student ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        Serach.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        Serach.setText("Search");
        Serach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SerachActionPerformed(evt);
            }
        });
        jPanel1.add(Serach, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, -1, -1));

        Practical.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        Practical.setForeground(new java.awt.Color(254, 254, 254));
        Practical.setText("Practical");
        jPanel1.add(Practical, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 580, -1, -1));

        jPanel2.setBackground(new java.awt.Color(254, 254, 254));
        jPanel2.setForeground(new java.awt.Color(254, 254, 254));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 490, 680, 10));

        Eligibility.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        Eligibility.setForeground(new java.awt.Color(254, 254, 254));
        Eligibility.setText("Eligibility");
        jPanel1.add(Eligibility, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, -1, -1));

        Attendance.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        Attendance.setForeground(new java.awt.Color(254, 254, 254));
        Attendance.setText("Attendance");
        jPanel1.add(Attendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 520, -1, -1));

        Pra.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        Pra.setForeground(new java.awt.Color(144, 254, 128));
        jPanel1.add(Pra, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 570, 170, 50));

        Att.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        Att.setForeground(new java.awt.Color(112, 254, 103));
        jPanel1.add(Att, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 510, 160, 50));

        PraCount.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        PraCount.setForeground(new java.awt.Color(254, 253, 91));
        jPanel1.add(PraCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 570, 150, 50));

        AttCount.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        AttCount.setForeground(new java.awt.Color(248, 255, 66));
        jPanel1.add(AttCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 510, 150, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        WelcomeLecturer lc = new WelcomeLecturer();
        lc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackActionPerformed

    private void SerachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SerachActionPerformed
        String id = StId.getText();
        String sub = SubId.getText();
         
        if(!sub.equals("") && !id.equals("")){
            try {
                Connection con=MyConnection.getConnection();
                String sql="select * from attendance where st_id='"+id+"' AND sub_id='"+sub+"'";
                PreparedStatement ps = con.prepareStatement(sql);
                ResultSet rs = ps.executeQuery();
                
                if(!sub.equals("TCS2112"))
                {
                    eligibility();
                }
                
                 if(sub.equals("TCS2112"))
                {
                    eligibility_TCS();
                }
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,"Please enter correct details!!!");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Please both fields!!!");
        }
    }//GEN-LAST:event_SerachActionPerformed
    
    void eligibility(){
        Eligibility ele = new Eligibility();
        
        String sub = SubId.getText();
        String id = StId.getText();
        
        float t = ele.getTheoryEligibility(id, sub);
        String countTh = String.format("%f", t);
        
        float p = ele.getPracticalEligibility(id, sub);
        String countPra = String.format("%f", p);
        
        ele.getTotalEligibility(id,sub);
        
        AttCount.setText(countTh);
        PraCount.setText(countPra);
        
        Att.setText(ele.getEligible(ele.getTheoryEligibility(id, sub)));
        Pra.setText(ele.getEligible(ele.getPracticalEligibility(id, sub)));  
    }
    
    void eligibility_TCS(){
        Eligibility ele = new Eligibility();
        
        String sub = SubId.getText();
        String id = StId.getText();
        
        float t = ele.getTheoryEligibility(id, sub);
        String countTh = String.format("%f", t);
        
        ele.getTotalEligibility(id,sub);
        
        AttCount.setText(countTh);
        PraCount.setText("-");
        
        Att.setText(ele.getEligible(ele.getTheoryEligibility(id, sub)));
        Pra.setText("-");
    } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentEligibility.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentEligibility.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentEligibility.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentEligibility.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentEligibility().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Att;
    private javax.swing.JLabel AttCount;
    private javax.swing.JLabel Attendance;
    private javax.swing.JButton Back;
    private javax.swing.JLabel Eligibility;
    private javax.swing.JLabel Pra;
    private javax.swing.JLabel PraCount;
    private javax.swing.JLabel Practical;
    private javax.swing.JButton Serach;
    private javax.swing.JTextField StId;
    private javax.swing.JTextField SubId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
