package techmis;


import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author tg375
 */
public class StudentViewFinalMarks extends javax.swing.JFrame {

    
    public StudentViewFinalMarks() {
        initComponents();
        subject();
    }

    
     PreparedStatement pdst;
     MyConnection con=new MyConnection();
     DefaultTableModel tmodel;
   
     StudentViewCA vc=new StudentViewCA();
     
     String stid;
     String sub;
     
     

     double CAtotal;
   StudentViewFinalMarks(double catotal) {
      this.CAtotal=catotal;
    }

   

   

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        stid_txt2 = new javax.swing.JTextField();
        sub_comb = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ca_table = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setPreferredSize(new java.awt.Dimension(900, 700));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("sid");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 68, 28));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("subject");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 100, 31));
        jPanel2.add(stid_txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 128, 38));

        jPanel2.add(sub_comb, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 128, 38));

        jButton2.setText("show  ca  result");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, 139, 54));

        jButton3.setText("clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, 99, 38));

        ca_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "StudentID", "Subject Code", "CA", "Grade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ca_table);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 610, 200));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setText("Final Marks");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          getmarks(get_text(stid),get_text2(sub));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        //clear raws in jtable
         for(int c=tmodel.getRowCount()-1;c>=0;c--){
                            tmodel.removeRow(c);
                        }
         
         //and clear the combo box and txtfield
         stid_txt2.setText("");
         sub_comb.setSelectedIndex(-1);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        StudentViewCA co = new StudentViewCA();  // back 
        co.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    //get subject names for combo box
    private void subject(){
        try {
            pdst=con.getConnection().prepareStatement("select * from subject");
             ResultSet rs=pdst.executeQuery();
             sub_comb.removeAllItems();
            
             while(rs.next()){
                 sub_comb.addItem(rs.getString(3));
             }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(StudentViewCA.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    
   //get subject code from database
    public String getdsubid(){
        
            String stid=stid_txt2.getText();
            String sub=sub_comb.getSelectedItem().toString();
            String subid="";
            String query1="select * from subjects  where sub_name=?";
            try {
                pdst=con.getConnection().prepareStatement(query1);
                pdst.setString(1, sub);
            
            ResultSet rs=pdst.executeQuery();
            if(rs.next()==false){
                JOptionPane.showMessageDialog(this, "Not Valid Subject Number");
            }else{
                while(rs.next()){
                    subid=rs.getString("sub_id");
                }
            }
            } catch (SQLException ex) {
                Logger.getLogger(StudentViewCA.class.getName()).log(Level.SEVERE, null, ex);
            }
            
       return subid;
    }
    
     public String get_text(String stid){ 
        stid=stid_txt2.getText();
        //sub=sub_comb.getSelectedItem().toString();
        return stid;
        
   }
   public String get_text2(String sub){ 
        //stid=stid_txt.getText();
        sub=sub_comb.getSelectedItem().toString();
        return sub;
        
   }
    
    
    
    
    private void getmarks(String stid,String sub){
       
        double theory= 0;
        double practical=0;
        String grade="";
        
        String subid="";
       
        
            
        String query1="select * from subjects  where sub_name=?";
        try {
                pdst=con.getConnection().prepareStatement(query1);
                pdst.setString(1, sub);
            
            ResultSet rs=pdst.executeQuery();
            while(rs.next()){
                subid=rs.getString("sub_id");
            
            }
            String query2="select * from final_exam_marks where sub_id=? and st_id=?";
        
            pdst=con.getConnection().prepareStatement(query2);
             pdst.setString(1, subid); 
             pdst.setString(2, stid);
            
            rs=pdst.executeQuery();
            
            //get result for result set
            while(rs.next()){
                practical=rs.getDouble("practical");
                theory=rs.getDouble("theory");
                
                    
            
            //get full ca marks total
            double Finaltotal=(theory+practical)/2;
            
            
            // check CA pass or fail
            String CAStatus;
            
            double catotal=vc.getmarks(get_text(stid),get_text2(sub));
            System.out.println(catotal);
            
            if(catotal>=50){
                CAStatus="PASS";
            }
            else{
                 CAStatus = "FAIL";
            }
            
            double marks=(catotal+Finaltotal)/2;
            
            //calculate grade
            if(CAStatus=="FAIL"){
               
                    grade="F";
            }
            else if(marks>=85){
                grade="A+";
            }
            else if(marks>=75){
                grade="A";
            }
            else if(marks>=70){
                grade="B+";
            }
            else if(marks>=65){
                grade="B";
            }
            else if(marks>=60){
                grade="C+";
            }
            else if(marks>=55){
                grade="C";
            }
            else if(marks>=50){
                grade="C-";
            }
            else if(marks>=45){
                grade="D+";
            }
             else if(marks>=35){
                grade="D-";
            }
            else{
                 grade="F";
             }
            
            
            tmodel=(DefaultTableModel)ca_table.getModel();
                    tmodel.addRow(new Object[]{
                        stid,
                        subid,
                        CAStatus,
                        grade
                        
                    });
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(StudentViewCA.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentViewCA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentViewCA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentViewCA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentViewCA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentViewFinalMarks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ca_table;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField stid_txt2;
    private javax.swing.JComboBox sub_comb;
    // End of variables declaration//GEN-END:variables
}
