/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
    package techmis;
    import java.sql.Connection;
    import java.sql.PreparedStatement;
    import java.sql.ResultSet;
    import java.sql.SQLException;
    import java.sql.Statement;
    import java.util.ArrayList;
    import java.util.logging.Level;
    import java.util.logging.Logger;
    import javax.swing.JOptionPane;
    import javax.swing.table.DefaultTableModel;
    import javax.swing.table.TableModel;

/**
 *
 * @author HUNTER
 */
public class ToaddCourse extends javax.swing.JFrame {
    Connection con = null;
    PreparedStatement pst = null;
    /**
     * Creates new form addCourse
     */
    public ToaddCourse() {
        initComponents();
        con = MyConnection.getConnection();
        show_course();
    }
    public ArrayList<ToCourse> courseList(){
        ArrayList<ToCourse> courseList = new ArrayList<>();
        try{
            String query1="SELECT * FROM course";
            Statement st= con.createStatement();
            ResultSet rs = st.executeQuery(query1);
            
            ToCourse course;
                while(rs.next()){
                    course=new ToCourse(rs.getString("co_id"),rs.getString("co_dept_id"),rs.getString("co_name"));
                    courseList.add(course);
                }
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        return courseList;
    }public void show_course(){
        ArrayList<ToCourse> list = courseList();
        DefaultTableModel model =(DefaultTableModel)display_course.getModel();
        Object[] row = new Object [3];
        for(int i=0;i<list.size();i++){
            row[0]= list.get(i).getco_id();
            row[1]= list.get(i).getco_dept_id();
            row[2]= list.get(i).getco_name();
            model.addRow(row);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        idbox = new javax.swing.JTextField();
        cordepid = new javax.swing.JTextField();
        namebox = new javax.swing.JTextField();
        addbutton = new javax.swing.JButton();
        updatebutton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        display_course = new javax.swing.JTable();
        deletebutton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("Course ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setText("Course Departmenr ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setText("Course Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));
        jPanel1.add(idbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 142, 150, 40));
        jPanel1.add(cordepid, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 150, 40));

        namebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameboxActionPerformed(evt);
            }
        });
        jPanel1.add(namebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 150, 40));

        addbutton.setText("ADD");
        addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(addbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, 100, 44));

        updatebutton.setText("UPDATE");
        updatebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebuttonActionPerformed(evt);
            }
        });
        jPanel1.add(updatebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, 100, 44));

        display_course.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "co_id", "co_dept_id", "co_name"
            }
        ));
        display_course.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                display_courseMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(display_course);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 550, 170));

        deletebutton.setText("DELETE");
        deletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebuttonActionPerformed(evt);
            }
        });
        jPanel1.add(deletebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, 100, 44));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 30, 90, 80));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("Course");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbuttonActionPerformed
        String CourseID = idbox.getText();
        String CorDepID =cordepid.getText();
        String CorName =namebox.getText();

        if(!CourseID.isEmpty()){
            if(!CorDepID.isEmpty()){
                if(!CorName.isEmpty()){

                try {
                    String sql="insert into course(co_id,co_dept_id,co_name) "
                    + " values('"+CourseID+"','"+CorDepID+"','"+CorName+"')";
                    pst = con.prepareStatement(sql);
                    pst.execute();
                    DefaultTableModel model = (DefaultTableModel)display_course.getModel();
                    model.setRowCount(0);
                    show_course();
                    JOptionPane.showMessageDialog(null,"Adding success");
                } catch (SQLException ex) {
                    Logger.getLogger(ToaddDepartment.class.getName()).log(Level.SEVERE, null, ex);
                }

            }else{
                    JOptionPane.showMessageDialog(null,"Insert Course Name","error", JOptionPane.ERROR_MESSAGE);
            }

        }else{
                JOptionPane.showMessageDialog(null,"Insert Course Department ID","error", JOptionPane.ERROR_MESSAGE);
        }
            
    }else{
            JOptionPane.showMessageDialog(null,"Insert Course ID","error", JOptionPane.ERROR_MESSAGE);
}

        // TODO add your handling code here:
    }//GEN-LAST:event_addbuttonActionPerformed

    private void nameboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameboxActionPerformed

    private void updatebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebuttonActionPerformed
        String CourseID = idbox.getText();
        String CorDepID =cordepid.getText();
        String CorName =namebox.getText();

        if(!CourseID.isEmpty()){
            if(!CorDepID.isEmpty()){
                if(!CorName.isEmpty()){
        
        try{
            int row =display_course.getSelectedRow();
            String value = (display_course.getModel().getValueAt(row, 0).toString());
            String query ="Update course set  co_dept_id ='"+CorDepID+"',co_name ='"+CorName+"' where co_id ='"+CourseID+"'";
            pst = con.prepareStatement(query);
            pst.execute();
            DefaultTableModel model = (DefaultTableModel)display_course.getModel();
                    model.setRowCount(0);
                    show_course();
                     JOptionPane.showMessageDialog(null,"Update success");
            
        }catch(Exception e){JOptionPane.showMessageDialog(null, e);
        
        }
                    }else{
                    JOptionPane.showMessageDialog(null,"Insert Course Name","error", JOptionPane.ERROR_MESSAGE);
            }

        }else{
                JOptionPane.showMessageDialog(null,"Insert Course Department ID","error", JOptionPane.ERROR_MESSAGE);
        }
            
    }else{
            JOptionPane.showMessageDialog(null,"Insert Course ID","error", JOptionPane.ERROR_MESSAGE);
}

        // TODO add your handling code here:
    }//GEN-LAST:event_updatebuttonActionPerformed

    private void display_courseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_display_courseMouseClicked
        int i = display_course.getSelectedRow();
        TableModel model =display_course.getModel();
        idbox.setText(model.getValueAt(i,0).toString());
        cordepid.setText(model.getValueAt(i,1).toString());
        namebox.setText(model.getValueAt(i,2).toString());
        // TODO add your handling code here:
    }//GEN-LAST:event_display_courseMouseClicked

    private void deletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebuttonActionPerformed
        String CourseID = idbox.getText();
        String CorDepID =cordepid.getText();
        String CorName =namebox.getText();

        if(!CourseID.isEmpty()){
            if(!CorDepID.isEmpty()){
               
        
        try{
           String query = "delete from course where co_id ='"+CourseID+"'";
            pst = con.prepareStatement(query);
            pst.execute();
            DefaultTableModel model = (DefaultTableModel)display_course.getModel();
                    model.setRowCount(0);
                    show_course();
                    JOptionPane.showMessageDialog(null,"Delete success");
            
        }catch(Exception e){JOptionPane.showMessageDialog(null, e);
        
        }
                    

        }else{
                JOptionPane.showMessageDialog(null,"Insert Course Department ID","error", JOptionPane.ERROR_MESSAGE);
        }
            
    }else{
            JOptionPane.showMessageDialog(null,"Insert Course ID","error", JOptionPane.ERROR_MESSAGE);
}
        

        // TODO add your handling code here:
    }//GEN-LAST:event_deletebuttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        welcomeTO w1 =new welcomeTO();
        w1.show();

        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ToaddCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ToaddCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ToaddCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ToaddCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ToaddCourse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbutton;
    private javax.swing.JTextField cordepid;
    private javax.swing.JButton deletebutton;
    private javax.swing.JTable display_course;
    private javax.swing.JTextField idbox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField namebox;
    private javax.swing.JButton updatebutton;
    // End of variables declaration//GEN-END:variables
}
