/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package techmis;
    import java.sql.Connection;
    import java.sql.PreparedStatement;
    import java.sql.ResultSet;
    import java.sql.SQLException;
    import java.sql.Statement;
    import java.util.ArrayList;
    import java.util.logging.Level;
    import java.util.logging.Logger;
    import javax.swing.JOptionPane;
    import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/**
 *
 * @author HUNTER
 */
public class ToaddDepartment extends javax.swing.JFrame {
    Connection con = null;
    PreparedStatement pst = null;
    /**
     * Creates new form addDepartment
     */
    public ToaddDepartment() {
        initComponents();
        con = MyConnection.getConnection();
        show_dep();
    }
    public ArrayList<ToUser> userList(){
        ArrayList<ToUser> userList = new ArrayList<>();
        try{
            String query1="SELECT * FROM department";
            Statement st= con.createStatement();
            ResultSet rs = st.executeQuery(query1);
            
            ToUser user;
                while(rs.next()){
                    user=new ToUser(rs.getString("d_id"),rs.getString("d_name"));
                    userList.add(user);
                }
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        return userList;
    }
    public void show_dep(){
        ArrayList<ToUser> list = userList();
        DefaultTableModel model =(DefaultTableModel)dispalay_dep.getModel();
        Object[] row = new Object [2];
        for(int i=0;i<list.size();i++){
            row[0]= list.get(i).getd_id();
            row[1]= list.get(i).getd_name();
            model.addRow(row);
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        idbox = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        namebox = new javax.swing.JTextField();
        addbutton1 = new javax.swing.JButton();
        updatebutton = new javax.swing.JButton();
        deletebutton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        dispalay_dep = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("Department");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));
        jPanel1.add(idbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 160, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("Department ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setText("Department Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, -1, -1));
        jPanel1.add(namebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 160, 50));

        addbutton1.setText("ADD");
        addbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbutton1ActionPerformed(evt);
            }
        });
        jPanel1.add(addbutton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 170, 120, 50));

        updatebutton.setText("UPDATE");
        updatebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebuttonActionPerformed(evt);
            }
        });
        jPanel1.add(updatebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 230, 120, 50));

        deletebutton.setText("DELETE");
        deletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebuttonActionPerformed(evt);
            }
        });
        jPanel1.add(deletebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 290, 120, 50));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, 90, 80));

        dispalay_dep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "d_id", "d_name"
            }
        ));
        dispalay_dep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dispalay_depMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(dispalay_dep);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 570, 150));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbutton1ActionPerformed
        String DepID = idbox.getText();
        String DepName =namebox.getText();

        if(!DepID.isEmpty()){
            if(!DepName.isEmpty()){

                try {
                    String sql="insert into department(d_id,d_name) "
                    + " values('"+DepID+"','"+DepName+"')";
                    pst = con.prepareStatement(sql);
                    pst.execute();
                    DefaultTableModel model = (DefaultTableModel)dispalay_dep.getModel();
                    model.setRowCount(0);
                    show_dep();
                   JOptionPane.showMessageDialog(null,"Adding success");
            
        }catch(Exception e){JOptionPane.showMessageDialog(null, e);
        
        }
        }else{
                JOptionPane.showMessageDialog(null,"Insert Department Name","error", JOptionPane.ERROR_MESSAGE);
            }

        }else{
            JOptionPane.showMessageDialog(null,"Insert Department ID","error", JOptionPane.ERROR_MESSAGE);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_addbutton1ActionPerformed

    private void dispalay_depMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dispalay_depMouseClicked
        
        int i = dispalay_dep.getSelectedRow();
        TableModel model =dispalay_dep.getModel();
        idbox.setText(model.getValueAt(i,0).toString());
        namebox.setText(model.getValueAt(i,1).toString());
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_dispalay_depMouseClicked

    private void updatebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebuttonActionPerformed
        String DepID = idbox.getText();
        String DepName =namebox.getText();

        if(!DepID.isEmpty()){
            if(!DepName.isEmpty()){
        
        try{
            int row =dispalay_dep.getSelectedRow();
            String value = (dispalay_dep.getModel().getValueAt(row, 0).toString());
            String query ="Update department set  d_name ='"+DepName+"' where d_id ='"+DepID+"'";
            pst = con.prepareStatement(query);
            pst.execute();
            DefaultTableModel model = (DefaultTableModel)dispalay_dep.getModel();
                    model.setRowCount(0);
                    show_dep();
            JOptionPane.showMessageDialog(null,"Update success");
            
        }catch(Exception e){JOptionPane.showMessageDialog(null, e);
        
        }
        }else{
                JOptionPane.showMessageDialog(null,"Insert Department Name","error", JOptionPane.ERROR_MESSAGE);
            }

        }else{
            JOptionPane.showMessageDialog(null,"Insert Department ID","error", JOptionPane.ERROR_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_updatebuttonActionPerformed

    private void deletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebuttonActionPerformed
        String DepID = idbox.getText();
        String DepName =namebox.getText();

        if(!DepID.isEmpty()){
            if(!DepName.isEmpty()){
        
        try{
           String query = "delete from department where d_id='"+DepID+"' and d_name='"+DepName+"'";
            pst = con.prepareStatement(query);
            pst.execute();
            DefaultTableModel model = (DefaultTableModel)dispalay_dep.getModel();
                    model.setRowCount(0);
                    show_dep();
                    JOptionPane.showMessageDialog(null,"Delete success");
            
        }catch(Exception e){JOptionPane.showMessageDialog(null, e);
        
        }
        }else{
                JOptionPane.showMessageDialog(null,"Insert Department Name","error", JOptionPane.ERROR_MESSAGE);
            }

        }else{
            JOptionPane.showMessageDialog(null,"Insert Department ID","error", JOptionPane.ERROR_MESSAGE);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_deletebuttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        welcomeTO w1 =new welcomeTO();
        w1.show();

        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ToaddDepartment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ToaddDepartment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ToaddDepartment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ToaddDepartment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ToaddDepartment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbutton1;
    private javax.swing.JButton deletebutton;
    private javax.swing.JTable dispalay_dep;
    private javax.swing.JTextField idbox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField namebox;
    private javax.swing.JButton updatebutton;
    // End of variables declaration//GEN-END:variables
}
