/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package techmis;

import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


/**
 *
 * @author HUNTER
 */
public class ToMedicalDetails extends javax.swing.JFrame {
    Connection con = null;
    PreparedStatement pst = null;
    /**
     * Creates new form MedicalDetailsShow
     */
    public ToMedicalDetails() {
        initComponents();
        con = MyConnection.getConnection();
        show_medical();
        
    }
    public ArrayList<ToMedical> medicalList(){
        ArrayList<ToMedical> medicalList = new ArrayList<>();
        try{
            String query1="SELECT * FROM medical";
            Statement st= con.createStatement();
            ResultSet rs = st.executeQuery(query1);
            
            ToMedical medical;
                while(rs.next()){
                    medical=new ToMedical(rs.getString("st_id"),rs.getString("sub_id"),rs.getDate("day"),rs.getString("type"),rs.getInt("hours"));
                    medicalList.add(medical);
                }
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        return medicalList;
    }public void show_medical(){
        ArrayList<ToMedical> list = medicalList();
        DefaultTableModel model =(DefaultTableModel)dispalaymedical.getModel();
        Object[] row = new Object [5];
        for(int i=0;i<list.size();i++){
            row[0]= list.get(i).getst_id();
            row[1]= list.get(i).getsub_id();
            row[2]= list.get(i).getday();
            row[3]= list.get(i).gettype();
            row[4]= list.get(i).gethours();
            model.addRow(row);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        stidbox = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        subidbox = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        daybox = new javax.swing.JTextField();
        typebox = new javax.swing.JTextField();
        hoursbox = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        addbutton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dispalaymedical = new javax.swing.JTable();
        updatebutton = new javax.swing.JButton();
        deletebutton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Medical Details");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 12, 390, 79));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setText("St_id");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 60, -1));
        jPanel1.add(stidbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 174, 54));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setText("Sub_ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, -1));

        subidbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subidboxActionPerformed(evt);
            }
        });
        jPanel1.add(subidbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 174, 52));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("Date");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 88, 55));

        daybox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayboxActionPerformed(evt);
            }
        });
        jPanel1.add(daybox, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 174, 52));
        jPanel1.add(typebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 174, 52));
        jPanel1.add(hoursbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 174, 52));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setText("Type");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(254, 254, 254));
        jLabel6.setText("Hours");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, -1, -1));

        addbutton.setText("ADD");
        addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(addbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, 110, 55));

        dispalaymedical.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "st_id ", "sub_id", "day", "type", "hours"
            }
        ));
        dispalaymedical.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dispalaymedicalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dispalaymedical);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 730, 200));

        updatebutton.setText("UPDATE");
        updatebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebuttonActionPerformed(evt);
            }
        });
        jPanel1.add(updatebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, 110, 55));

        deletebutton.setText("DELETE");
        deletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebuttonActionPerformed(evt);
            }
        });
        jPanel1.add(deletebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 280, 110, 55));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 30, 90, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subidboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subidboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subidboxActionPerformed

    private void dispalaymedicalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dispalaymedicalMouseClicked
        int i = dispalaymedical.getSelectedRow();
        TableModel model =dispalaymedical.getModel();
        stidbox.setText(model.getValueAt(i,0).toString());
        subidbox.setText(model.getValueAt(i,1).toString());
        daybox.setText(model.getValueAt(i,2).toString());
        typebox.setText(model.getValueAt(i,3).toString());
        hoursbox.setText(model.getValueAt(i,4).toString());
    

        // TODO add your handling code here:
    }//GEN-LAST:event_dispalaymedicalMouseClicked

    private void addbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbuttonActionPerformed
        String StuID = stidbox.getText();
        String SubID =subidbox.getText();
        String day =daybox.getText();
        String type =typebox.getText();
        String hours =hoursbox.getText();
        if(!StuID.isEmpty()){
            if(!SubID.isEmpty()){
                if(!day.isEmpty()){
                    if(!type.isEmpty()){
                        if(!hours.isEmpty()){

                try {
                    String sql="insert into medical(st_id,sub_id,day,type,hours) "
                    + " values('"+StuID+"','"+SubID+"','"+day+"','"+type+"','"+hours+"')";
                    pst = con.prepareStatement(sql);
                    pst.execute();
                    DefaultTableModel model = (DefaultTableModel)dispalaymedical.getModel();
                    model.setRowCount(0);
                    show_medical();
                    JOptionPane.showMessageDialog(null,"Adding success");
                } catch (SQLException ex) {
                    Logger.getLogger(ToaddDepartment.class.getName()).log(Level.SEVERE, null, ex);
                }
                                }else{
                                    JOptionPane.showMessageDialog(null,"Insert Course Hours","error", JOptionPane.ERROR_MESSAGE);
                            }
                        }else{
                            JOptionPane.showMessageDialog(null,"Insert Course Type","error", JOptionPane.ERROR_MESSAGE);
            }

            }else{
                    JOptionPane.showMessageDialog(null,"Insert Course Name","error", JOptionPane.ERROR_MESSAGE);
            }

        }else{
                JOptionPane.showMessageDialog(null,"Insert Course Department ID","error", JOptionPane.ERROR_MESSAGE);
        }
            
    }else{
            JOptionPane.showMessageDialog(null,"Insert Course ID","error", JOptionPane.ERROR_MESSAGE);
}

        // TODO add your handling code here:
    }//GEN-LAST:event_addbuttonActionPerformed

    private void dayboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dayboxActionPerformed

    private void updatebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebuttonActionPerformed
        String StuID = stidbox.getText();
        String SubID =subidbox.getText();
        String day =daybox.getText();
        String type =typebox.getText();
        String hours =hoursbox.getText();

        if(!StuID.isEmpty()){
            if(!SubID.isEmpty()){
                if(!day.isEmpty()){
                    if(!type.isEmpty()){
                        if(!hours.isEmpty()){
        
        try{
            int row =dispalaymedical.getSelectedRow();
            String value = (dispalaymedical.getModel().getValueAt(row, 0).toString());
            String query ="Update medical set  day ='"+day+"',type ='"+type+"',hours ='"+hours+"' where st_id ='"+StuID+"' and sub_id ='"+SubID+"'";
            pst = con.prepareStatement(query);
            pst.execute();
            DefaultTableModel model = (DefaultTableModel)dispalaymedical.getModel();
                    model.setRowCount(0);
                    show_medical();
                    JOptionPane.showMessageDialog(null,"Update Success");
            
        }catch(Exception e){JOptionPane.showMessageDialog(null, e);
        
        }
                                   }else{
                                    JOptionPane.showMessageDialog(null,"Insert Course Hours","error", JOptionPane.ERROR_MESSAGE);
                            }
                        }else{
                            JOptionPane.showMessageDialog(null,"Insert Course Type","error", JOptionPane.ERROR_MESSAGE);
            }

            }else{
                    JOptionPane.showMessageDialog(null,"Insert Course Name","error", JOptionPane.ERROR_MESSAGE);
            }

        }else{
                JOptionPane.showMessageDialog(null,"Insert Course Department ID","error", JOptionPane.ERROR_MESSAGE);
        }
            
    }else{
            JOptionPane.showMessageDialog(null,"Insert Course ID","error", JOptionPane.ERROR_MESSAGE);
}

        // TODO add your handling code here:
    }//GEN-LAST:event_updatebuttonActionPerformed

    private void deletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebuttonActionPerformed

        String StuID = stidbox.getText();
        String SubID =subidbox.getText();
        String day =daybox.getText();
        String type =typebox.getText();
        String hours =hoursbox.getText();

        if(!StuID.isEmpty()){
            if(!SubID.isEmpty()){
                if(!day.isEmpty()){
                    if(!type.isEmpty()){
                        if(!hours.isEmpty()){
               
        
        try{
           String query = "delete from medical where st_id ='"+StuID+"'and sub_id ='"+SubID+"' and day ='"+day+"' and type ='"+type+"' and hours ='"+hours+"'";
            pst = con.prepareStatement(query);
            pst.execute();
            DefaultTableModel model = (DefaultTableModel)dispalaymedical.getModel();
                    model.setRowCount(0);
                    show_medical();
                    JOptionPane.showMessageDialog(null,"Delete Success");
            
        }catch(Exception e){JOptionPane.showMessageDialog(null, e);
        
        }
                                   }else{
                                    JOptionPane.showMessageDialog(null,"Insert Course Hours","error", JOptionPane.ERROR_MESSAGE);
                            }
                        }else{
                            JOptionPane.showMessageDialog(null,"Insert Course Type","error", JOptionPane.ERROR_MESSAGE);
            }

            }else{
                    JOptionPane.showMessageDialog(null,"Insert Course Name","error", JOptionPane.ERROR_MESSAGE);
            }

        }else{
                JOptionPane.showMessageDialog(null,"Insert Course Department ID","error", JOptionPane.ERROR_MESSAGE);
        }
            
    }else{
            JOptionPane.showMessageDialog(null,"Insert Course ID","error", JOptionPane.ERROR_MESSAGE);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_deletebuttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        welcomeTO w1 =new welcomeTO();
        w1.show();

        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ToMedicalDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ToMedicalDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ToMedicalDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ToMedicalDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ToMedicalDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbutton;
    private javax.swing.JTextField daybox;
    private javax.swing.JButton deletebutton;
    private javax.swing.JTable dispalaymedical;
    private javax.swing.JTextField hoursbox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField stidbox;
    private javax.swing.JTextField subidbox;
    private javax.swing.JTextField typebox;
    private javax.swing.JButton updatebutton;
    // End of variables declaration//GEN-END:variables
}
