/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package techmis;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author HUNTER
 */
public class ToStudentAdd extends javax.swing.JFrame {
    Connection con = null;
    PreparedStatement pst = null;

    /**
     * Creates new form toStuInsert
     */
    public ToStudentAdd() {
        
        initComponents();
        con = MyConnection.getConnection();
        show_student();
    }
    public ArrayList<ToStudent> studentList(){
        ArrayList<ToStudent> studentList = new ArrayList<>();
        try{
            String query1="SELECT * FROM student";
            Statement st= con.createStatement();
            ResultSet rs = st.executeQuery(query1);
            
            ToStudent student;
                while(rs.next()){
                                student=new ToStudent(rs.getString("st_id"),rs.getString("st_d_id"),rs.getString("menter_id"),rs.getString("st_name"),rs.getString("st_address"),rs.getString("gender"),rs.getString("st_b_day"),rs.getString("st_p_no"));
                    studentList.add(student);
                }
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        return studentList;
    }public void show_student(){
        ArrayList<ToStudent> list = studentList();
        DefaultTableModel model =(DefaultTableModel)displaystudent.getModel();
        Object[] row = new Object [8];
        for(int i=0;i<list.size();i++){
            row[0]= list.get(i).getst_id();
            row[1]= list.get(i).getst_d_id();
            row[2]= list.get(i).getmenter_id();
            row[3]= list.get(i).getst_name();
            row[4]= list.get(i).getst_address();
            row[5]= list.get(i).getgender();
            row[6]= list.get(i).getst_b_day();
            row[7]= list.get(i).getst_p_no();
            model.addRow(row);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        regno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        deletebutton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        department = new javax.swing.JTextField();
        phone_no = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        menter_id = new javax.swing.JTextField();
        dob = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        updatebutton = new javax.swing.JButton();
        gender = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Addbutton = new javax.swing.JButton();
        name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        displaystudent = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, 90, 80));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setText("Students");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 230, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(254, 254, 254));
        jLabel9.setText("Phone No");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(254, 254, 254));
        jLabel7.setText("Gender");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, -1, -1));

        regno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regnoActionPerformed(evt);
            }
        });
        jPanel1.add(regno, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 184, 41));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("Department");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        deletebutton.setText("DELETE");
        deletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebuttonActionPerformed(evt);
            }
        });
        jPanel1.add(deletebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 126, 47));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(254, 254, 254));
        jLabel6.setText("Address");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));
        jPanel1.add(department, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 184, 41));

        phone_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phone_noActionPerformed(evt);
            }
        });
        jPanel1.add(phone_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, 184, 41));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setText("Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, -1, -1));

        menter_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menter_idActionPerformed(evt);
            }
        });
        jPanel1.add(menter_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, 184, 41));

        dob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobActionPerformed(evt);
            }
        });
        jPanel1.add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 184, 41));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(254, 254, 254));
        jLabel8.setText("Birth Day");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        updatebutton.setText("UPDATE");
        updatebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebuttonActionPerformed(evt);
            }
        });
        jPanel1.add(updatebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 100, 47));

        gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderActionPerformed(evt);
            }
        });
        jPanel1.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, 184, 41));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("Rgistration Number");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        Addbutton.setText("ADD");
        Addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(Addbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, 110, 50));

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 150, 184, 41));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setText("Menter ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, -1, -1));

        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });
        jPanel1.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 184, 41));

        displaystudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "st_id", "st_d_id", "menter_id ", "st_name", "st_address	", "gender", "st_b_day", "st_p_no"
            }
        ));
        displaystudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                displaystudentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(displaystudent);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 710, 260));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void menter_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menter_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menter_idActionPerformed

    private void genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderActionPerformed

    private void regnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regnoActionPerformed

    private void dobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dobActionPerformed

    private void AddbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddbuttonActionPerformed

        String stuRegno = regno.getText();
        String stuDepartment = department.getText();
        String stuMenter_id = menter_id.getText();
        String studentName = name.getText();
        String stuAddress = address.getText();
        String stuGender = gender.getText();
        String stuDOB = dob.getText();
        String stuP_no = phone_no.getText();

        if(!stuRegno.isEmpty()){
            if(!stuDepartment.isEmpty()){
                if(!stuMenter_id.isEmpty()){
                    if(!studentName.isEmpty()){
                        if(!stuAddress.isEmpty()){
                            if(!stuGender.isEmpty()){
                                if(!stuDOB.isEmpty()){
                                    if(!stuP_no.isEmpty()){

                                        try {
                                            String sql="insert into student(st_id,st_d_id,menter_id,st_name,st_address,gender,st_b_day,st_p_no) "
                                                    + " values('"+stuRegno+"','"+stuDepartment+"','"+stuMenter_id+"','"+studentName+"','"+stuAddress+"','"+stuGender+"','"+stuDOB+"','"+stuP_no+"')";
                                            pst = con.prepareStatement(sql);
                                            pst.execute();
                                            DefaultTableModel model = (DefaultTableModel)displaystudent.getModel();
                                            model.setRowCount(0);
                                            show_student();
                                            JOptionPane.showMessageDialog(null,"Adding succsess");

                                        } catch (SQLException ex) {
                                            Logger.getLogger(ToStudentAdd.class.getName()).log(Level.SEVERE, null, ex);
                                        }

                                    }else{
                                        JOptionPane.showMessageDialog(null,"Insert phone ","error", JOptionPane.ERROR_MESSAGE);

                                    }

                                }else{
                                    JOptionPane.showMessageDialog(null,"Insert birth day","error", JOptionPane.ERROR_MESSAGE);

                                }

                            }else{
                                JOptionPane.showMessageDialog(null,"Insert gender","error", JOptionPane.ERROR_MESSAGE);

                            }

                        }else{
                            JOptionPane.showMessageDialog(null,"Insert address","error", JOptionPane.ERROR_MESSAGE);

                        }

                    }else{
                        JOptionPane.showMessageDialog(null,"Insert name","error", JOptionPane.ERROR_MESSAGE);

                    }

                }else{
                    JOptionPane.showMessageDialog(null,"Insert menta id","error", JOptionPane.ERROR_MESSAGE);

                }

            }else{
                JOptionPane.showMessageDialog(null,"Insert department","error", JOptionPane.ERROR_MESSAGE);

            }

        }else{
            JOptionPane.showMessageDialog(null,"Insert Register number","error", JOptionPane.ERROR_MESSAGE);

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_AddbuttonActionPerformed

    private void phone_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phone_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phone_noActionPerformed

    private void updatebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebuttonActionPerformed

        String stuRegno = regno.getText();
        String stuDepartment = department.getText();
        String stuMenter_id = menter_id.getText();
        String studentName = name.getText();
        String stuAddress = address.getText();
        String stuGender = gender.getText();
        String stuDOB = dob.getText();
        String stuP_no = phone_no.getText();

        if(!stuRegno.isEmpty()){
            if(!stuDepartment.isEmpty()){
                if(!stuMenter_id.isEmpty()){
                    if(!studentName.isEmpty()){
                        if(!stuAddress.isEmpty()){
                            if(!stuGender.isEmpty()){
                                if(!stuDOB.isEmpty()){
                                    if(!stuP_no.isEmpty()){

                                        try {
                                            String sql="Update student set st_d_id ='"+stuDepartment+"',"
                                                    + "menter_id ='"+stuMenter_id+"', "
                                                    + "st_name ='"+studentName+"',"
                                                    + "st_address ='"+stuAddress+"',"
                                                    + "gender ='"+stuGender+"',"
                                                    + "st_b_day ='"+stuDOB+"',"
                                                    + "st_p_no ='"+stuP_no+"'"
                                                    + "where st_id ='"+stuRegno+"'";
                                           
                                            pst = con.prepareStatement(sql);
                                            pst.execute();
                                            DefaultTableModel model = (DefaultTableModel)displaystudent.getModel();
                                            model.setRowCount(0);
                                            show_student();
                                            JOptionPane.showMessageDialog(null,"update succsess");

                                        } catch (SQLException ex) {
                                            Logger.getLogger(ToStudentAdd.class.getName()).log(Level.SEVERE, null, ex);
                                        }

                                    }else{
                                        JOptionPane.showMessageDialog(null,"Insert phone ","error", JOptionPane.ERROR_MESSAGE);

                                    }

                                }else{
                                    JOptionPane.showMessageDialog(null,"Insert birth day","error", JOptionPane.ERROR_MESSAGE);

                                }

                            }else{
                                JOptionPane.showMessageDialog(null,"Insert gender","error", JOptionPane.ERROR_MESSAGE);

                            }

                        }else{
                            JOptionPane.showMessageDialog(null,"Insert address","error", JOptionPane.ERROR_MESSAGE);

                        }

                    }else{
                        JOptionPane.showMessageDialog(null,"Insert name","error", JOptionPane.ERROR_MESSAGE);

                    }

                }else{
                    JOptionPane.showMessageDialog(null,"Insert menta id","error", JOptionPane.ERROR_MESSAGE);

                }

            }else{
                JOptionPane.showMessageDialog(null,"Insert department","error", JOptionPane.ERROR_MESSAGE);

            }

        }else{
            JOptionPane.showMessageDialog(null,"Insert Register number","error", JOptionPane.ERROR_MESSAGE);

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_updatebuttonActionPerformed

    private void displaystudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_displaystudentMouseClicked

        int i = displaystudent.getSelectedRow();
        TableModel model =displaystudent.getModel();
        regno.setText(model.getValueAt(i,0).toString());
        department.setText(model.getValueAt(i,1).toString());
        menter_id.setText(model.getValueAt(i,2).toString());
        name.setText(model.getValueAt(i,3).toString());
        address.setText(model.getValueAt(i,4).toString());
        gender.setText(model.getValueAt(i,5).toString());
        dob.setText(model.getValueAt(i,6).toString());
        phone_no.setText(model.getValueAt(i,7).toString());

        // TODO add your handling code here:
    }//GEN-LAST:event_displaystudentMouseClicked

    private void deletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebuttonActionPerformed

         String stuRegno = regno.getText();
        String stuDepartment = department.getText();
        String stuMenter_id = menter_id.getText();
        String studentName = name.getText();
        String stuAddress = address.getText();
        String stuGender = gender.getText();
        String stuDOB = dob.getText();
        String stuP_no = phone_no.getText();

        if(!stuRegno.isEmpty()){
            if(!stuDepartment.isEmpty()){
                if(!stuMenter_id.isEmpty()){
                    if(!studentName.isEmpty()){
                        if(!stuAddress.isEmpty()){
                            if(!stuGender.isEmpty()){
                                if(!stuDOB.isEmpty()){
                                    if(!stuP_no.isEmpty()){

                                        try {
           String query = "delete from student where st_id ='"+stuRegno+"'";
            pst = con.prepareStatement(query);
            pst.execute();
            DefaultTableModel model = (DefaultTableModel)displaystudent.getModel();
                    model.setRowCount(0);
                    show_student();
                    JOptionPane.showMessageDialog(null,"Delete success");
            
        }catch (SQLException ex) {
                                            Logger.getLogger(ToStudentAdd.class.getName()).log(Level.SEVERE, null, ex);
                                        }

                                    }else{
                                        JOptionPane.showMessageDialog(null,"Insert phone ","error", JOptionPane.ERROR_MESSAGE);

                                    }

                                }else{
                                    JOptionPane.showMessageDialog(null,"Insert birth day","error", JOptionPane.ERROR_MESSAGE);

                                }

                            }else{
                                JOptionPane.showMessageDialog(null,"Insert gender","error", JOptionPane.ERROR_MESSAGE);

                            }

                        }else{
                            JOptionPane.showMessageDialog(null,"Insert address","error", JOptionPane.ERROR_MESSAGE);

                        }

                    }else{
                        JOptionPane.showMessageDialog(null,"Insert name","error", JOptionPane.ERROR_MESSAGE);

                    }

                }else{
                    JOptionPane.showMessageDialog(null,"Insert menta id","error", JOptionPane.ERROR_MESSAGE);

                }

            }else{
                JOptionPane.showMessageDialog(null,"Insert department","error", JOptionPane.ERROR_MESSAGE);

            }

        }else{
            JOptionPane.showMessageDialog(null,"Insert Register number","error", JOptionPane.ERROR_MESSAGE);

        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_deletebuttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    welcomeTO w1 =new welcomeTO();
    w1.show();
    
    dispose();
        
    // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ToStudentAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ToStudentAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ToStudentAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ToStudentAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ToStudentAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addbutton;
    private javax.swing.JTextField address;
    private javax.swing.JButton deletebutton;
    private javax.swing.JTextField department;
    private javax.swing.JTable displaystudent;
    private javax.swing.JTextField dob;
    private javax.swing.JTextField gender;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField menter_id;
    private javax.swing.JTextField name;
    private javax.swing.JTextField phone_no;
    private javax.swing.JTextField regno;
    private javax.swing.JButton updatebutton;
    // End of variables declaration//GEN-END:variables
}
